//   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#include<iostream>
using namespace std;

int main()
{
    long long t1 = 1;
    long long t2 = 2;

    long long nt = t1 + t2;
    long long int sum = 2;
    while(nt<4000000)
    {
        if(nt%2 == 0)
        {
            sum += nt;
        }
        t1= t2;
        t2 = nt;
        nt = t1+t2;
    }
    cout<<sum;
}
